name: graphrag
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.10.16
  - debugpy=1.8.12
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pywin32=307
  - pyzmq=26.2.1
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - async-timeout==4.0.3
      - attrs==25.1.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - et-xmlfile==2.0.0
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - idna==3.10
      - jinja2==3.1.5
      - jiter==0.8.2
      - json-repair==0.39.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - langchain==0.3.25
      - langchain-community==0.3.24
      - langchain-core==0.3.60
      - langchain-neo4j==0.4.0
      - langchain-openai==0.3.6
      - langchain-text-splitters==0.3.8
      - langsmith==0.3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - mysql-connector-python==9.3.0
      - narwhals==1.27.1
      - neo4j==5.28.1
      - neo4j-driver==5.28.1
      - neo4j-graphrag==1.7.0
      - numpy==1.26.4
      - openai==1.63.2
      - openpyxl==3.1.5
      - orjson==3.10.15
      - pandas==2.2.3
      - pillow==11.1.0
      - plotly==6.0.1
      - propcache==0.3.0
      - protobuf==5.29.3
      - pyarrow==19.0.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.8.0
      - pydeck==0.9.1
      - pymysql==1.1.1
      - pyparsing==3.2.3
      - pypdf==5.5.0
      - python-dotenv==1.0.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.23.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.38
      - streamlit==1.42.2
      - tenacity==9.0.0
      - tiktoken==0.9.0
      - toml==0.10.2
      - tqdm==4.67.1
      - types-pyyaml==6.0.12.20250516
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - watchdog==6.0.0
      - yarl==1.18.3
      - zstandard==0.23.0
