# rename this file to `secrets.toml` and delete this comment line

[mysql]
user     = "<mysql_username>"
password = "<mysql_password>"
host     = "<mysql_host>"
port     = <mysql_port>
database = "<mysql_database_name>"

[neo4j]
NEO4J_URI       = "<your_neo4j_uri>"
NEO4J_USERNAME  = "<neo4j_username>"
NEO4J_PASSWORD  = "<neo4j_password>"

[openai]
OPENAI_API_KEY  = "<your_api_key>"